apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-vpc-cni
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karannagwekar/gitops-repository
    targetRevision: deployment
    path: gitops/apps/aws-vpc-cni
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: DaemonSet
    jsonPointers:
    - /spec/template/spec/containers/0/resources
