apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto-east
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karannagwekar/gitops-repository
    targetRevision: deployment
    path: gitops/apps/emojivoto
  destination:
    server: https://kubernetes.default.svc
    namespace: emojivoto
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
