apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-west
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karannagwekar/gitops-repository
    targetRevision: deployment
    path: gitops/apps/traefik
  destination:
    server: https://4210F439DEA0F901D2E1F0DA11D6701A.gr7.us-west-2.eks.amazonaws.com
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
